global:
  resolve_timeout: 5m

receivers:
  - name: "webhook"
    webhook_configs:
      - url: "http://service-registry-api:8085/api/alerts/webhook"
        send_resolved: true
        http_config:
          follow_redirects: true

  - name: "default"

inhibit_rules:
  - source_matchers:
      - severity="critical"
    target_matchers:
      - severity="warning"
    equal: ["alertname", "instance"]

route:
  receiver: "webhook"
  group_by: ["alertname", "severity", "service"]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h

  routes:
    - matchers:
        - severity="critical"
      receiver: "webhook"
      group_wait: 5s
      repeat_interval: 5m

    - matchers:
        - severity="warning"
      receiver: "webhook"
      group_wait: 30s
      repeat_interval: 30m

    - matchers:
        - severity="info"
      receiver: "default"
